# "Need Tests":
# - any: ['**']
#   all: ['!__tests__/**']

# the following example does not work
# @domain/core:
# - package/core/*
# - package/core/**/*

# Removing labels
# bug:
# - non-existent-file.txt
# invalid:
# - non-existent-file.txt

# Match all files
"Tests failed":
  - '**'
  - '.*'
  - '.*/**'
