# "Need Tests":
# - any: ['**']
#   all: ['!__tests__/**']

# the following example does not work
# @domain/core:
# - package/core/*
# - package/core/**/*

Label1:
- non-existent-file.txt

Label2:
- non-existent-file.txt
