name: "Remove label"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      id: tests
      run: |
        Start-Sleep -Seconds 30
        exit 1
      shell: pwsh
    
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
      if: ${{ steps.tests.conclusion == 'failure' }}
